# Generated by Django 3.2.4 on 2024-12-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicalname', models.CharField(max_length=255)),
                ('referrerCode', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('salesMapping', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCollectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patientname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('age_type', models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('patientname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(max_length=10)),
                ('sample_collector', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('discount', models.CharField(blank=True, max_length=100)),
                ('lab_id', models.CharField(blank=True, max_length=50)),
                ('refby', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('B2B', models.CharField(blank=True, max_length=100)),
                ('home_collection', models.CharField(blank=True, max_length=100)),
                ('testname', models.JSONField(max_length=100)),
                ('totalAmount', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('credit_amount', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RefBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('confirmPassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('patientname', models.CharField(max_length=100)),
                ('B2B', models.CharField(blank=True, max_length=100, null=True)),
                ('home_collection', models.CharField(max_length=100)),
                ('testdetails', models.JSONField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, unique=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('reference_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('patientname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('testdetails', models.JSONField()),
            ],
        ),
    ]
